begin;

create table if not exists public.admins (
  admin_id bigint generated by default as identity primary key,
  email varchar(255) not null unique,
  password varchar(255) not null,
  first_name varchar(255),
  last_name varchar(255),
  created_at timestamp
);

delete from public.users
where email in ('admin1@renteasy.com', 'admin2@renteasy.com');

do $$
declare
  item record;
begin
  for item in
    select conname
    from pg_constraint
    where conrelid = 'public.cart_items'::regclass
      and contype = 'f'
  loop
    execute format('alter table public.cart_items drop constraint if exists %I', item.conname);
  end loop;
end $$;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'cart_items' and column_name = 'id'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'cart_items' and column_name = 'cart_item_id'
  ) then
    alter table public.cart_items rename column id to cart_item_id;
  end if;
end $$;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users' and column_name = 'userid'
  ) and exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users' and column_name = 'user_id'
  ) then
    alter table public.users drop column user_id;
    alter table public.users rename column userid to user_id;
  elsif exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users' and column_name = 'userid'
  ) then
    alter table public.users rename column userid to user_id;
  end if;
end $$;

alter table public.users drop column if exists role;
alter table public.users add column if not exists phone varchar(255);

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'productid'
  ) and exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'product_id'
  ) then
    alter table public.products drop column product_id;
    alter table public.products rename column productid to product_id;
  elsif exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'productid'
  ) then
    alter table public.products rename column productid to product_id;
  end if;
end $$;

alter table public.products add column if not exists image_url text;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'image'
  ) then
    update public.products
    set image_url = image
    where (image_url is null or image_url = '') and image is not null;

    alter table public.products drop column image;
  end if;
end $$;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'cart_items' and column_name = 'quantity'
  ) and exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'cart_items' and column_name = 'days'
  ) then
    update public.cart_items
    set days = coalesce(days, quantity, 1);

    alter table public.cart_items drop column quantity;
  elsif exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'cart_items' and column_name = 'quantity'
  ) then
    alter table public.cart_items rename column quantity to days;
  end if;
end $$;

alter table public.cart_items add column if not exists days integer;
update public.cart_items set days = 1 where days is null or days < 1;
alter table public.cart_items alter column days set default 1;
alter table public.cart_items alter column days set not null;

alter table public.cart_items add column if not exists user_id bigint;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'cart_items' and column_name = 'user_email'
  ) then
    update public.cart_items ci
    set user_id = u.user_id
    from public.users u
    where ci.user_email = u.email;

    alter table public.cart_items drop column user_email;
  end if;
end $$;

delete from public.cart_items
where user_id is null or product_id is null;

delete from public.cart_items a
using public.cart_items b
where a.cart_item_id > b.cart_item_id
  and a.user_id = b.user_id
  and a.product_id = b.product_id;

alter table public.cart_items alter column user_id set not null;
alter table public.cart_items alter column product_id set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'fk_cart_items_user'
  ) then
    alter table public.cart_items
    add constraint fk_cart_items_user
    foreign key (user_id) references public.users(user_id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'fk_cart_items_product'
  ) then
    alter table public.cart_items
    add constraint fk_cart_items_product
    foreign key (product_id) references public.products(product_id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'uq_cart_items_user_product'
  ) then
    alter table public.cart_items
    add constraint uq_cart_items_user_product unique (user_id, product_id);
  end if;
end $$;

create table if not exists public.rental_orders (
  order_id bigint generated by default as identity primary key,
  order_number varchar(255) not null unique,
  user_id bigint not null references public.users(user_id) on delete cascade,
  subtotal numeric(12, 2),
  service_fee numeric(12, 2),
  total numeric(12, 2),
  status varchar(255),
  delivery_name varchar(255),
  delivery_email varchar(255),
  delivery_phone varchar(255),
  delivery_address varchar(255),
  delivery_city varchar(255),
  delivery_zip varchar(255),
  created_at timestamp
);

alter table public.rental_orders add column if not exists delivery_name varchar(255);
alter table public.rental_orders add column if not exists delivery_email varchar(255);
alter table public.rental_orders add column if not exists delivery_phone varchar(255);
alter table public.rental_orders add column if not exists delivery_address varchar(255);
alter table public.rental_orders add column if not exists delivery_city varchar(255);
alter table public.rental_orders add column if not exists delivery_zip varchar(255);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'rental_orders'
      and column_name = 'shipping_name'
  ) then
    update public.rental_orders
    set
      delivery_name = coalesce(delivery_name, shipping_name),
      delivery_email = coalesce(delivery_email, shipping_email),
      delivery_phone = coalesce(delivery_phone, shipping_phone),
      delivery_address = coalesce(delivery_address, shipping_address),
      delivery_city = coalesce(delivery_city, shipping_city),
      delivery_zip = coalesce(delivery_zip, shipping_zip);
  end if;
end $$;

alter table public.rental_orders drop column if exists shipping_name;
alter table public.rental_orders drop column if exists shipping_email;
alter table public.rental_orders drop column if exists shipping_phone;
alter table public.rental_orders drop column if exists shipping_address;
alter table public.rental_orders drop column if exists shipping_city;
alter table public.rental_orders drop column if exists shipping_zip;

create table if not exists public.rental_order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references public.rental_orders(order_id) on delete cascade,
  product_id bigint references public.products(product_id) on delete set null,
  product_name varchar(255),
  price numeric(12, 2),
  days integer not null default 1
);

commit;
